CREATE TABLE IF NOT EXIST 'dive_shop' (
    DIVE_SHOP_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PROVINCE VARCHAR(255) NOT NULL,
    CITY VARCHAR(255) NOT NULL,
    ZIP_CODE VARCHAR(255) NOT NULL,
    DETAIL VARCHAR(255),
    PHONE_NUMBER VARCHAR(255),
    FAX VARCHAR(255),
    COMMENT VARCHAR(500),
    RESERVE_COUNT INT NOT NULL,
    AVAILABLE_TIME VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);